services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/instance:/app/instance
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:5000

  db-viewer:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      # - ./backend/instance/reactiverange.db:/app/reactiverange.db
      - ./backend:/data
    environment:
      # - SQLITE_DATABASE=reactiverange.db
      - SQLITE_DATABASE=instance/reactiverange.db
    restart: always
